### PR TITLE
Multiple improvements on EKS and logging stacks

### PR DESCRIPTION
**Pull request by pmoranga**
Improve the following:
- EKS: 
  - Support for custom log retention using Cloudwatch
  - Allow to pass custom AWS Tags to EKS Nodes
  - Bump TF Module to latest minor from major version used.
- Logging:
  - Bump version of ElasticSeach module
  - Set IOPS when not GP2 volume
  - Allow to change instance types
- Cache (Redis)
  - bumped version of module used
  - Pinned the TF and AWS provider versions to avoid breaking changes.
- Many of the submodules
  - Pinned the TF and AWS provider versions to avoid breaking changes.

### CODE REVIEW

**Comment by davidcheung** [comment]
@pmoranga Thanks for so many improvements! 

looks like they [replaced `source_json`  with `source_policy_documents`](https://github.com/hashicorp/terraform-provider-aws/issues/22906) and this broke `user_access` module, and perhaps the grouping is hiding the `exit code 1` maybe we'll need to shortcurcuit the validate whenever 1 module exits with `1`

**Comment by pmoranga** [comment]
Hi @davidcheung I fixed the `and` operators and captured the exit codes of each command and issue the exit code at the end of the shell.

Please review.

The current error seems related to the GH Token, can you fix this on your side ?

**Comment by davidcheung** [comment]
Thanks @pmoranga!!  
yeah i wonder if the perms were put in the wrong place https://github.com/commitdev/terraform-aws-zero/commit/8e093929a4734f35cd7b8cfb8b4459fb4ea51d26 since the job was still setup with the wrong perms 
image

but i think we can force merge without that

**Review by davidcheung — APPROVED** [review]
Thanks!

**Comment by pmoranga** [comment]
> Thanks @pmoranga!! yeah i wonder if the perms were put in the wrong place [8e09392](https://github.com/commitdev/terraform-aws-zero/commit/8e093929a4734f35cd7b8cfb8b4459fb4ea51d26) since the job was still setup with the wrong perms image
> 
> but i think we can force merge without that
> 
> edit they do say its a top level key, i wonder why it doesnt honor it 🤔 https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

The permission from the GH Action may be capped at the Repository Settings: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository , maybe worth checking on your side.

**Comment by davidcheung** [comment]
yeah thanks @pmoranga  i dont have visibility into the org settings, the repo settings looks good (and i've basically tried all of them), ill ask around to see if i can find out what the org version of this settings look like 
image

**Pull request merged**
